# api 服务
server {
  listen 80;
  server_name api.spotecreadonly129.net api.spotec129.net.au api.spotec129.net api.spotec129v2.net;
  location ~ /api/(ib|app|client|h5|third|home)/ {
    proxy_pass http://127.0.0.1:31000;
    proxy_set_header X-Client-IP $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #proxy_set_header X-Forwarded-For $remote_addr;
    proxy_connect_timeout 60;
    proxy_read_timeout 600;
    # 从当前nginx过的流量都携带B版本,流量仅在B路线消费
    proxy_set_header instanceVersion b;

    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Access-Control-Allow-Headers;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS';
    add_header Access-Control-Allow-Headers *;
    if ($request_method = 'OPTIONS') {
      return 204;
    }
  }


  location ^~ /mt4/ws/ {
    # 官网ws端口是31000
    proxy_pass http://127.0.0.1:31000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_connect_timeout 10s;
    proxy_send_timeout 60s;
    proxy_read_timeout 3600s;
  }

  location ^~ /mt4/ {
    proxy_pass http://127.0.0.1:31000;
    proxy_set_header X-Client-IP $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout 60;
    proxy_read_timeout 600;
    # 从当前nginx过的流量都携带A版本,流量仅在A路线消费
    #proxy_set_header instanceVersion a;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS';
    add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,lang,platform,token';
    if ($request_method = 'OPTIONS') {
      return 204;
    }
  }

  location ^~ /api/websocket/ {
    proxy_pass http://127.0.0.1:31000;
    proxy_set_header X-Client-IP $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout 60;
    proxy_read_timeout 600;
    # 从当前nginx过的流量都携带A版本,流量仅在A路线消费
    #proxy_set_header instanceVersion a;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS';
    add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,lang,platform,token';
    if ($request_method = 'OPTIONS') {
      return 204;
    }
  }

  location /mt4/trade.io/ {
    #proxy_pass http://127.0.0.1:31000;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_pass http://172.31.45.245:30012;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location ^~ /ws/ {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    # 客户端ws端口是30000
    proxy_pass http://127.0.0.1:30013;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  access_log /var/log/nginx/client-api.log combined;
  error_log /var/log/nginx/client-api-error.log;
}
