
upstream backend {
  server localhost:9030;
  server localhost:9080;
}

map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

# crm 服务
server {
  server_name crm.spotecreadonly129.net crm.spotec129.net.au crm.spotec129v2.net crm.spotec129.net;
  listen 80;
  location / {
    proxy_intercept_errors on;
    proxy_pass http://backend;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Client-IP $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_connect_timeout 5s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;
  }

  location = /robots.txt {
    default_type text/plain;

    if ($host ~* ^crm\.ecmarkets\.(sc|com|com\.au|co\.nz|mu)$) {
      return 200 "User-agent: *\nAllow: /\n";
    }

    return 200 "User-agent: *\nDisallow: /\n";
  }

  error_page 502 503 504 /50x.html;
  location = /50x.html {
    root /etc/nginx/error_page;
  }

  access_log /var/log/nginx/pc-web.log combined;
  error_log /var/log/nginx/pc-web-error.log;
}

# 代理服务
server {
  listen 9000;
  index index.html ;
  root /data/fee/application/tools;
  try_files $uri $uri/ /index.html;
}

# 官网
server {
  listen 80;
  server_name www.spotec129.net;

  location / {
    proxy_intercept_errors on;
    proxy_pass http://192.168.0.129:9010;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Client-IP $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_connect_timeout 5s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;
  }

  error_page 502 503 504 /50x.html;
  location = /50x.html {
    root /etc/nginx/error_page;
  }
}

# 文件服务
server {
  listen 80;
  server_name file.spotecreadonly129.net file.spotec129.net file.spotec129v2.net;
  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host 192.168.0.129:9000;

    proxy_connect_timeout 300;
    # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    chunked_transfer_encoding off;

    proxy_pass http://192.168.0.129:9000;
  }
}

# 落地页
server {
  listen 80;
  server_name r.spotec129.net;

  root /data/fee/application/tmd-landing-page/current;
  index index.html;

  try_files $uri $uri/ /index.html;

  # 清除潜在旧头
  add_header Content-Security-Policy "" always;
  add_header Content-Security-Policy-Report-Only "" always;
  add_header X-Frame-Options "" always;

  # 正确允许 iframe
  add_header Content-Security-Policy "frame-ancestors http: https:" always;
}

# webview
server {
  server_name m.spotec129.net;
  listen 80;
  location / {
    proxy_intercept_errors on;
    proxy_pass http://localhost:6060;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Client-IP $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_connect_timeout 5s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;
  }

  location = /robots.txt {
    default_type text/plain;

    if ($host ~* ^crm\.ecmarkets\.(sc|com|com\.au|co\.nz|mu)$) {
      return 200 "User-agent: *\nAllow: /\n";
    }

    return 200 "User-agent: *\nDisallow: /\n";
  }

  error_page 502 503 504 /50x.html;
  location = /50x.html {
    root /etc/nginx/error_page;
  }

  access_log /var/log/nginx/mobile-web.log combined;
  error_log /var/log/nginx/mobile-web-error.log;
}
